from collections import Counter
from datetime import timedelta

from django.utils import timezone
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from ai.models import EmailPrediction, ExtractedTask
from ai.services.contextual_search import search_mail_context
from ai.services.priority import calculate_priority_score
from ai.services.task_inference import extract_tasks_from_email
from ai.services.urgency_inference import predict_urgency
from ai.utils.project_grouping import infer_project_name
from ai.utils.task_metadata import extract_deadline_hint, extract_responsibility_hint
from emails.models import EmailMessage

try:
    from ai.services.intent_inference import predict_intent

    INTENT_AVAILABLE = True
except Exception:
    INTENT_AVAILABLE = False


def _serialize_prediction(prediction):
    if not prediction:
        return None
    return {
        "urgency": prediction.urgency,
        "urgency_confidence": prediction.urgency_confidence,
        "intent": prediction.intent,
        "intent_confidence": prediction.intent_confidence,
        "priority_score": prediction.priority_score,
    }


def _serialize_task(task):
    return {
        "id": task.id,
        "task_text": task.task_text,
        "confidence": task.confidence,
        "status": task.status,
        "deadline": task.deadline,
        "responsibility": task.responsibility,
    }


def _analyze_single_email(user, email):
    body_text = email.full_body_text or email.snippet or ""
    project_name = infer_project_name(email.subject or "", body_text)
    if project_name and project_name != email.project_name:
        email.project_name = project_name
        email.save(update_fields=["project_name"])

    urgency_result = predict_urgency(email.subject or "", body_text)

    intent_result = None
    if INTENT_AVAILABLE:
        try:
            intent_result = predict_intent(email.subject or "", body_text)
        except Exception:
            intent_result = None

    urgency = urgency_result.get("urgency")
    urgency_conf = urgency_result.get("confidence")

    intent = intent_result.get("intent") if intent_result else None
    intent_conf = intent_result.get("confidence") if intent_result else None

    priority_score = calculate_priority_score(urgency, intent)

    prediction, _ = EmailPrediction.objects.update_or_create(
        user=user,
        email=email,
        defaults={
            "urgency": urgency,
            "urgency_confidence": urgency_conf,
            "intent": intent,
            "intent_confidence": intent_conf,
            "priority_score": priority_score,
            "explanation": "Generated by integrated AI models and MailMind report-aligned enrichment.",
        },
    )

    task_results = extract_tasks_from_email(body_text, threshold=0.50)
    ExtractedTask.objects.filter(user=user, email=email).delete()

    created_tasks = []
    body_deadline = extract_deadline_hint(body_text)
    body_owner = extract_responsibility_hint(body_text)

    for item in task_results:
        deadline = extract_deadline_hint(item["task_text"]) or body_deadline
        responsibility = extract_responsibility_hint(item["task_text"]) or body_owner

        task = ExtractedTask.objects.create(
            user=user,
            email=email,
            task_text=item["task_text"],
            confidence=item["score"],
            deadline=deadline,
            responsibility=responsibility,
        )
        created_tasks.append(_serialize_task(task))

    return prediction, created_tasks


@api_view(["POST"])
@permission_classes([IsAuthenticated])
def analyze_email(request, gmail_id):
    email = EmailMessage.objects.filter(user=request.user, gmail_id=gmail_id).first()
    if not email:
        return Response({"error": "Email not found"}, status=404)

    prediction, created_tasks = _analyze_single_email(request.user, email)

    return Response(
        {
            "gmail_id": gmail_id,
            "project_name": email.project_name,
            "prediction": _serialize_prediction(prediction),
            "tasks": created_tasks,
        }
    )


@api_view(["POST"])
@permission_classes([IsAuthenticated])
def analyze_latest_emails(request):
    limit = int(request.data.get("limit", 20))

    emails = (
        EmailMessage.objects.filter(user=request.user)
        .order_by("-internal_date", "-created_at")[:limit]
    )

    analyzed = 0
    for email in emails:
        _analyze_single_email(request.user, email)
        analyzed += 1

    return Response({"analyzed": analyzed})


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def list_tasks(request):
    tasks = (
        ExtractedTask.objects.filter(user=request.user)
        .select_related("email")
        .order_by("-created_at")
    )

    data = []
    for task in tasks:
        data.append(
            {
                "id": task.id,
                "gmail_id": task.email.gmail_id,
                "task_text": task.task_text,
                "confidence": task.confidence,
                "status": task.status,
                "deadline": task.deadline,
                "responsibility": task.responsibility,
                "project_name": task.email.project_name,
                "email_subject": task.email.subject,
                "email_sender": task.email.sender,
            }
        )

    return Response({"tasks": data})


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def priority_emails(request):
    predictions = (
        EmailPrediction.objects.filter(user=request.user)
        .select_related("email")
        .order_by("-priority_score", "-created_at")
    )

    emails = []
    for prediction in predictions:
        email = prediction.email
        deadline = (
            email.tasks.exclude(deadline__isnull=True)
            .exclude(deadline__exact="")
            .values_list("deadline", flat=True)
            .first()
        )
        emails.append(
            {
                "gmail_id": email.gmail_id,
                "sender": email.sender,
                "subject": email.subject,
                "project_name": email.project_name,
                "urgency": prediction.urgency,
                "intent": prediction.intent,
                "priority_score": prediction.priority_score,
                "deadline": deadline,
            }
        )

    return Response({"emails": emails})


def _weekday_activity(emails):
    order = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    counts = {name: 0 for name in order}
    for email in emails:
        if email.internal_date:
            counts[email.internal_date.strftime("%a")] += 1
    return [{"name": name, "emails": counts[name]} for name in order]


def _weekly_urgency_trend(predictions):
    now = timezone.now()
    start_of_week = (now - timedelta(days=now.weekday())).replace(hour=0, minute=0, second=0, microsecond=0)
    buckets = []
    for index in range(3, -1, -1):
        week_start = start_of_week - timedelta(weeks=index)
        week_end = week_start + timedelta(days=7)
        bucket_preds = [
            pred
            for pred in predictions
            if (pred.email.internal_date or pred.created_at) and week_start <= (pred.email.internal_date or pred.created_at) < week_end
        ]
        urgency_counter = Counter(pred.urgency for pred in bucket_preds if pred.urgency)
        buckets.append(
            {
                "name": f"W{4 - index}",
                "high": urgency_counter.get("High", 0),
                "medium": urgency_counter.get("Medium", 0),
                "low": urgency_counter.get("Low", 0),
            }
        )
    return buckets


def _active_contacts(emails):
    counts = Counter(email.sender for email in emails if email.sender)
    results = []
    for sender, count in counts.most_common(5):
        initials = "".join(part[0] for part in sender.split()[:2]).upper() or "MM"
        results.append(
            {
                "name": sender,
                "count": count,
                "initials": initials[:2],
            }
        )
    return results


def _top_projects(emails):
    counts = Counter(email.project_name for email in emails if email.project_name)
    return [{"name": name, "count": count} for name, count in counts.most_common(5)]


def _task_status_distribution(tasks):
    counts = Counter(task.status for task in tasks if task.status)
    return dict(counts)


def _recent_insights(urgency_counts, intent_counts, tasks, emails):
    insights = []
    total_urgent = urgency_counts.get("High", 0)
    if total_urgent:
        insights.append(
            {
                "title": "Urgency load detected",
                "description": f"{total_urgent} emails are marked high urgency and should be triaged first.",
            }
        )

    if intent_counts:
        top_intent, top_count = intent_counts.most_common(1)[0]
        insights.append(
            {
                "title": "Dominant intent class",
                "description": f"{top_intent} is the most common intent across analyzed emails ({top_count} messages).",
            }
        )

    deadline_count = sum(1 for task in tasks if task.deadline)
    if deadline_count:
        insights.append(
            {
                "title": "Deadline cues extracted",
                "description": f"{deadline_count} tasks include deadline hints captured from email content.",
            }
        )

    project_count = len({email.project_name for email in emails if email.project_name})
    if project_count:
        insights.append(
            {
                "title": "Project-based grouping active",
                "description": f"MailMind has grouped the inbox into {project_count} active project threads.",
            }
        )

    return insights[:4]


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def ai_summary(request):
    predictions = list(
        EmailPrediction.objects.filter(user=request.user).select_related("email").order_by("-created_at")
    )
    emails = list(
        EmailMessage.objects.filter(user=request.user).select_related("prediction").order_by("-internal_date", "-created_at")
    )
    tasks = list(
        ExtractedTask.objects.filter(user=request.user).select_related("email").order_by("-created_at")
    )

    urgency_counts = Counter(pred.urgency for pred in predictions if pred.urgency)
    intent_counts = Counter(pred.intent for pred in predictions if pred.intent)

    return Response(
        {
            "total_predictions": len(predictions),
            "total_emails": len(emails),
            "attachments_received": sum(1 for email in emails if "HAS_ATTACHMENT" in (email.labels or "")),
            "project_count": len({email.project_name for email in emails if email.project_name}),
            "urgency_distribution": dict(urgency_counts),
            "intent_distribution": dict(intent_counts),
            "pending_tasks": sum(1 for task in tasks if task.status == "Pending"),
            "total_tasks": len(tasks),
            "task_status_distribution": _task_status_distribution(tasks),
            "tasks_with_deadline": sum(1 for task in tasks if task.deadline),
            "activity_timeline": _weekday_activity(emails),
            "weekly_urgency_trend": _weekly_urgency_trend(predictions),
            "most_active_contacts": _active_contacts(emails),
            "top_projects": _top_projects(emails),
            "recent_insights": _recent_insights(urgency_counts, intent_counts, tasks, emails),
        }
    )


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def contextual_search(request):
    query = request.GET.get("q", "").strip()
    if not query:
        return Response(
            {
                "query": "",
                "matched_emails": [],
                "related_attachments": [],
                "related_tasks": [],
                "detected_context": {},
            }
        )

    queryset = (
        EmailMessage.objects.filter(user=request.user)
        .select_related("prediction")
        .prefetch_related("tasks")
        .order_by("-internal_date", "-created_at")[:300]
    )
    return Response(search_mail_context(request.user, queryset, query))
