# Generated by Django 6.0.2 on 2026-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='full_body_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
