# Generated by Django 6.0.2 on 2026-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailmessage_full_body_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
