# Generated by Django 6.0.2 on 2026-03-31 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emailmessage_project_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='gmail_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='emails.gmailcredential'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='source_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gmailcredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('user', 'gmail_id', 'source_email')},
        ),
        migrations.AlterUniqueTogether(
            name='gmailcredential',
            unique_together={('user', 'email_address')},
        ),
    ]
