# Generated by Django 6.0.2 on 2026-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_emailprediction_intent_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtask',
            name='responsibility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
