# Generated by Django 6.0.2 on 2026-03-22 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, default='', max_length=120)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='profile_photos/')),
                ('notify_urgent', models.BooleanField(default=True)),
                ('notify_deadlines', models.BooleanField(default=True)),
                ('notify_digest', models.BooleanField(default=False)),
                ('notify_attachments', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
